import './styles.css';

const Tickets = () => {
  return (
    <>
       {/* Header */}
    <header className="p-4 relative z-10 mt-18">
        <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
                {/* <a href="index.html" className="text-white hover:text-orange-400 transition-colors">
                    ← Back
                </a> */}
                <h1 className="text-xl font-bold orbitron">Select Numbers</h1>
            </div>
            <div className="text-sm text-gray-300">
                <span id="total-cost">$0</span>
            </div>
        </div>
    </header>

     {/* Main Content */}
    <div className="p-4 pb-32">
        {/* Selected Numbers Display  */}
        <div className="glass-card rounded-2xl p-6 mb-6 text-center">
            <h2 className="text-lg font-semibold mb-4 text-gray-300">Your Selection</h2>
            {/* <div className="grid grid-cols-2 gap-4">
                <div>
                    <div className="text-sm text-gray-400 mb-1">Bitcoin</div>
                    <div className="selected-display orbitron" id="selected-bitcoin">--</div>
                </div>
                <div>
                    <div className="text-sm text-gray-400 mb-1">Ethereum</div>
                    <div className="selected-display orbitron" id="selected-ethereum">--</div>
                </div>
            </div>
            <div className="mt-4">
                <button className="quick-pick-button px-4 py-2 rounded-lg text-sm font-medium" onclick="quickPick()">
                    🎲 Quick Pick
                </button>
            </div> */}
        </div>

        {/*  Bitcoin Number Selection
        <div className="crypto-section">
            <div className="section-title bitcoin-title">
                <img src="resources/bitcoin-icon.svg" alt="Bitcoin" className="w-6 h-6"/>
                <span>Select Bitcoin Last 2 Digits</span>
            </div>
            <div className="glass-card rounded-2xl p-4">
                <div className="number-grid" id="bitcoin-grid">
                      Numbers 00-99 will be generated by JavaScript  
                </div>
            </div>
        </div>

         Ethereum Number Selection
        <div className="crypto-section">
            <div className="section-title ethereum-title">
                <img src="resources/ethereum-icon.svg" alt="Ethereum" className="w-6 h-6"/>
                <span>Select Ethereum Last 2 Digits</span>
            </div>
            <div className="glass-card rounded-2xl p-4">
                <div className="number-grid" id="ethereum-grid">
                     Numbers 00-99 will be generated by JavaScript 
                </div>
            </div>
        </div> */}

        {/* Ticket Options */}
        <div className="glass-card rounded-2xl p-6 mb-6">
            <h3 className="text-lg font-semibold mb-4">Ticket Options</h3>
            {/* <div className="space-y-4">
                <div>
                    <label className="block text-sm font-medium mb-2 text-gray-300">Number of Tickets</label>
                    <select className="w-full px-4 py-3 rounded-lg bg-white bg-opacity-10 border border-white border-opacity-20 text-white" id="ticket-count">
                        <option value="1">1 Ticket - $5 each</option>
                        <option value="5">5 Tickets - $4.50 each</option>
                        <option value="10">10 Tickets - $4 each</option>
                        <option value="20">20 Tickets - $3.50 each</option>
                        <option value="50">50 Tickets - $3 each</option>
                    </select>
                </div>
                <div className="flex justify-between items-center pt-2">
                    <span className="text-gray-300">Total Cost:</span>
                    <span className="text-2xl font-bold orbitron" id="total-cost-display">$0</span>
                </div>
            </div> */}
        </div>
    </div>

     {/* Sticky Purchase Button  */}
    {/* <div className="ticket-summary px-4">
        <button id="purchase-button" className="buy-button w-full py-4 rounded-lg text-white font-bold text-lg orbitron disabled:opacity-50 disabled:cursor-not-allowed" disabled>
            SELECT NUMBERS TO CONTINUE
        </button>
    </div> */}
    </>
  )
}

export default Tickets